meta_product_name: "shufflethis!"
meta_title: "shufflethis! - The hottest spotify shuffle algorithm you didn't even know you needed!"
meta_description: "shufflethis! takes your spotify playlists and reorders them in a way that all those tracks you feel like you are hearing way too often, will less likely be played.
Finally you will be getting from your playlists what they were supposed to deliver to you all this time!"
meta_image: "cover.png"
